// ============================================================
//  MicroMMO — data.js
// ============================================================

export function slug(n){return n.toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"");}

export const UI={
  LOGO:{emoji:"⚔",image:"img/ui/logo.svg"},
  WALK_BTN:{emoji:"⚔️",image:""},NAV_HOME:{emoji:"🏠",image:""},
  NAV_GEAR:{emoji:"🎒",image:""},NAV_MARKET:{emoji:"🏪",image:""},NAV_SOCIAL:{emoji:"👥",image:""},
};
export const PLAYER_AVATAR={emoji:"🧙",image:""};

export const CFG={
  BASE_ENERGY:25,ENERGY_PER_5_LEVELS:1,ENERGY_REGEN_MS:1*60*1000,
  MONSTER_CHANCE:0.30,GOLD_CHANCE:0.22,ITEM_CHANCE:0.13,CHOICE_EVENT_CHANCE:0.12,
  WALK_EGG_CHANCE:0.005,
  MARKET_FEE:0.05,PVP_GOLD_STEAL:0.10,PVP_COOLDOWN_MS:4*60*60*1000,
  ARENA_COST_GOLD:200,ARENA_COST_EP:1,POTION_HEAL_SMALL:0.3,POTION_HEAL_BIG:0.7,
  AVATAR_DROP_CHANCE:0.04,SHOP_SELL_RATE:0.20,
  PROPERTY_SELL_RATE:0.80,PROPERTY_STACK_FEE:0.05,
  CHEST_BASE_PRICE:500,CHEST_PRICE_SCALE:1.25,CHEST_EGG_CHANCE:0.05,
  COMBAT_VICTORY_CLOSE_MS:3000,GUILD_CREATE_COST:5000,GUILD_MAX_MEMBERS:10,
  GUILD_RAID_COST:1000,BOUNTY_MIN:500,
  SALVAGE_SHARDS_BASE:3,UPGRADE_SHARD_COST:5,UPGRADE_GOLD_COST_PER_VAL:20,UPGRADE_MAX_TIMES:10,
  STEP_XP_BASE:3,STEP_XP_PER_LEVEL:0.5,
  COMBO_TIERS:[1,5,15,30],COMBO_MULTS:[1,1.1,1.2,1.3],COMBO_DECAY_ON_DEATH:true,
  CHEST_EGG_RARITY:{common:45,uncommon:25,rare:15,epic:10,legendary:5},
  DUNGEON_CHEST_EGG_CHANCE:0.20,
};

export const EQUIP_SLOTS=["Helmet","Armour","Weapon","Shield","Greaves","Boots","Amulet","Pet"];
export const SLOT_EMOJI={Helmet:"🪖",Armour:"🦺",Weapon:"⚔️",Shield:"🛡️",Greaves:"🦵",Boots:"👢",Amulet:"💍",Pet:"🐾"};
export const RARITY_COLOR={common:"#6b7280",uncommon:"#059669",rare:"#2563eb",epic:"#7c3aed",legendary:"#d97706"};
export const RARITY_SCALE={common:0.8,uncommon:1.2,rare:1.8,epic:2.5,legendary:3.5};
export const TIER_EMOJIS=["🪙","🥉","🥈","🥇","💠","💎","👑"];
export const GUILD_ROLES={leader:"Leader",admin:"Admin",member:"Member"};

export const ARENA_TIERS=[
  {name:"Copper",  color:"#cd7f32",wins:0,  expBonus:1.0, goldBonus:1.0},
  {name:"Bronze",  color:"#c9943a",wins:10, expBonus:1.1, goldBonus:1.1},
  {name:"Silver",  color:"#94a3b8",wins:25, expBonus:1.25,goldBonus:1.2},
  {name:"Gold",    color:"#f59e0b",wins:50, expBonus:1.4, goldBonus:1.35},
  {name:"Platinum",color:"#60a5fa",wins:100,expBonus:1.6, goldBonus:1.5},
  {name:"Diamond", color:"#c084fc",wins:200,expBonus:1.85,goldBonus:1.7},
  {name:"Champion",color:"#fbbf24",wins:400,expBonus:2.2, goldBonus:2.0},
];

export const WEATHER_TYPES=[
  {id:"clear",    name:"Clear Skies",    emoji:"☀️", desc:"A fine day for adventuring.",    goldMult:1.0,expMult:1.0, monsterMult:1.0,lootMult:1.0,color:"#fbbf24"},
  {id:"rain",     name:"Heavy Rain",     emoji:"🌧️", desc:"Gold washes out of the mud.",    goldMult:1.4,expMult:1.0, monsterMult:0.8,lootMult:1.1,color:"#60a5fa"},
  {id:"fog",      name:"Thick Fog",      emoji:"🌫️", desc:"Monsters lurk unseen.",          goldMult:1.2,expMult:1.1, monsterMult:1.3,lootMult:1.2,color:"#94a3b8"},
  {id:"bloodmoon",name:"Blood Moon",     emoji:"🌑", desc:"Double danger. Double glory.",   goldMult:1.5,expMult:1.5, monsterMult:1.6,lootMult:1.4,color:"#ef4444"},
  {id:"blessing", name:"Divine Blessing",emoji:"✨", desc:"The gods smile upon you today.", goldMult:1.2,expMult:1.5, monsterMult:0.9,lootMult:1.5,color:"#c084fc"},
];

export const WALK_AREAS=[
  {id:"greenwood",    name:"Greenwood Vale",   emoji:"🌲",desc:"A peaceful forest. Beware the shadows.",minLevel:1,  monsterMinLv:1,  monsterMaxLv:8,  expMult:1.0,goldMult:1.0,lootBonus:0,   bgCSS:`background:linear-gradient(180deg,#0d2b1a 0%,#1a4a2a 50%,#0f2a18 100%);`,particles:"leaves"},
  {id:"stonecrypt",   name:"Stone Crypt",      emoji:"💀",desc:"Ancient burial grounds. The dead don't rest.",minLevel:5,  monsterMinLv:5,  monsterMaxLv:14, expMult:1.3,goldMult:1.2,lootBonus:0.05,bgCSS:`background:linear-gradient(180deg,#0e0e1a 0%,#1a1a2e 50%,#0a0a14 100%);`,particles:"spirits"},
  {id:"shadowpeaks",  name:"Shadow Peaks",     emoji:"⛰️",desc:"Treacherous mountains. Monsters roam freely.",minLevel:10, monsterMinLv:10, monsterMaxLv:22, expMult:1.7,goldMult:1.5,lootBonus:0.08,bgCSS:`background:linear-gradient(180deg,#0a0814 0%,#1a1030 50%,#080612 100%);`,particles:"snow"},
  {id:"voidrift",     name:"The Void Rift",    emoji:"🌀",desc:"Reality tears here. Only legends survive.",minLevel:18, monsterMinLv:18, monsterMaxLv:35, expMult:2.2,goldMult:2.0,lootBonus:0.12,bgCSS:`background:linear-gradient(180deg,#050514 0%,#0a0520 50%,#020208 100%);`,particles:"void"},
  {id:"ashvolcano",   name:"Ashveil Volcano",  emoji:"🌋",desc:"Rivers of lava. The air burns your lungs.",minLevel:25, monsterMinLv:25, monsterMaxLv:50, expMult:2.6,goldMult:2.4,lootBonus:0.15,bgCSS:`background:linear-gradient(180deg,#1a0500 0%,#3a0f00 50%,#0f0200 100%);`,particles:"embers"},
  {id:"frostspire",   name:"Frostspire Wastes",emoji:"🧊",desc:"Eternal blizzard. Only the cold survives.",minLevel:32, monsterMinLv:32, monsterMaxLv:65, expMult:3.0,goldMult:2.8,lootBonus:0.18,bgCSS:`background:linear-gradient(180deg,#050a14 0%,#0a1428 50%,#050a1a 100%);`,particles:"blizzard"},
  {id:"shadowrealm",  name:"Shadow Realm",     emoji:"👁️",desc:"A dimension of pure darkness and terror.",minLevel:40, monsterMinLv:40, monsterMaxLv:80, expMult:3.5,goldMult:3.2,lootBonus:0.22,bgCSS:`background:linear-gradient(180deg,#080008 0%,#150015 50%,#050005 100%);`,particles:"shadow"},
  {id:"celestialplane",name:"Celestial Plane", emoji:"✨",desc:"The realm of gods. Few mortals see this and live.",minLevel:50, monsterMinLv:50, monsterMaxLv:100,expMult:4.0,goldMult:3.8,lootBonus:0.28,bgCSS:`background:linear-gradient(180deg,#0a0820 0%,#181030 50%,#080618 100%);`,particles:"stars"},
  {id:"abyssaldepths",name:"Abyssal Depths",   emoji:"🌊",desc:"The ocean floor. Ancient horrors dwell here.",minLevel:60, monsterMinLv:60, monsterMaxLv:130,expMult:4.8,goldMult:4.5,lootBonus:0.35,bgCSS:`background:linear-gradient(180deg,#000814 0%,#001428 50%,#000510 100%);`,particles:"bubbles"},
  {id:"chaoscore",    name:"The Chaos Core",   emoji:"☄️",desc:"The end of all things. Pure destruction incarnate.",minLevel:75, monsterMinLv:75, monsterMaxLv:200,expMult:6.0,goldMult:5.5,lootBonus:0.45,bgCSS:`background:linear-gradient(180deg,#0f0000 0%,#1f0505 50%,#0a0000 100%);`,particles:"chaos"},
];

export const PROPERTIES=[
  {id:"prop_hovel",   name:"Wanderer's Hovel",  emoji:"🪨",price:500,   energyBonus:2,  rentalRate:0.05,desc:"A damp cave you've claimed."},
  {id:"prop_shack",   name:"Rustic Shack",       emoji:"🛖",price:1500,  energyBonus:5,  rentalRate:0.05,desc:"Four walls and a leaky roof."},
  {id:"prop_cottage", name:"Stoneleaf Cottage",  emoji:"🏡",price:4000,  energyBonus:10, rentalRate:0.05,desc:"A cozy cottage by a brook."},
  {id:"prop_inn",     name:"Traveller's Inn",    emoji:"🏠",price:10000, energyBonus:18, rentalRate:0.05,desc:"A proper inn. Guests pay."},
  {id:"prop_manor",   name:"Thornwood Manor",    emoji:"🏰",price:25000, energyBonus:30, rentalRate:0.05,desc:"A sprawling manor."},
  {id:"prop_keep",    name:"Ironspire Keep",     emoji:"🗼",price:60000, energyBonus:50, rentalRate:0.05,desc:"A fortified keep."},
  {id:"prop_citadel", name:"Celestial Citadel",  emoji:"✨",price:150000,energyBonus:100,rentalRate:0.05,desc:"Touched by the gods."},
];

export const SHOP_CONSUMABLES=[
  {id:"potion_small", name:"Minor Healing Potion",emoji:"🧪",desc:"Restores 30% max HP",price:120,effect:"heal_small"},
  {id:"potion_big",   name:"Major Healing Potion", emoji:"💊",desc:"Restores 70% max HP",price:350,effect:"heal_big"},
  {id:"energy_refill",name:"Energy Crystal",       emoji:"⚡",desc:"Refills all energy",  price:200,effect:"energy_full"},
  {id:"exp_scroll",   name:"Tome of Knowledge",    emoji:"📜",desc:"Grants 200 EXP",      price:500,effect:"exp_200"},
];

export const MONSTERS=[
  {name:"Goblin Scout",    emoji:"👺",desc:"A sneaky little menace.",    str:[5,1.2], def:[2,0.8], hp:[30,6],    exp:[10,2.5], gold:[3,1.5],  areaIds:["greenwood","stonecrypt"]},
  {name:"Forest Wolf",     emoji:"🐺",desc:"Runs in packs. Alone now.", str:[8,1.5], def:[3,1.0], hp:[45,8],    exp:[25,3.5], gold:[8,2.0],  areaIds:["greenwood","stonecrypt","shadowpeaks"]},
  {name:"Cave Bat",        emoji:"🦇",desc:"Dives from the dark.",       str:[6,1.3], def:[2,0.8], hp:[25,5],    exp:[15,2.5], gold:[4,1.5],  areaIds:["greenwood","stonecrypt"]},
  {name:"Stone Golem",     emoji:"🗿",desc:"Slow but devastating.",      str:[10,1.8],def:[15,2.0],hp:[80,12],   exp:[40,5.0], gold:[15,2.5], areaIds:["stonecrypt","shadowpeaks"]},
  {name:"Shadow Wraith",   emoji:"👻",desc:"Feeds on life force.",       str:[18,2.5],def:[5,1.2], hp:[60,10],   exp:[55,6.5], gold:[20,3.5], areaIds:["stonecrypt","shadowpeaks","voidrift"]},
  {name:"Venomfang Spider",emoji:"🕷️",desc:"Its bite carries rot.",      str:[14,2.0],def:[6,1.4], hp:[55,9],    exp:[35,4.5], gold:[12,2.5], areaIds:["stonecrypt","shadowpeaks"]},
  {name:"Troll Brute",     emoji:"👹",desc:"Regenerates. Hit it fast.",  str:[20,2.8],def:[12,2.0],hp:[110,16],  exp:[60,7.0], gold:[25,4.0], areaIds:["shadowpeaks","voidrift"]},
  {name:"Dragon Whelp",    emoji:"🐉",desc:"Young dragon. Still lethal.",str:[26,3.2],def:[10,2.0],hp:[120,18],  exp:[80,9.0], gold:[35,5.5], areaIds:["shadowpeaks","voidrift","ashvolcano"]},
  {name:"Skeleton Knight", emoji:"💀",desc:"Fought a hundred wars.",     str:[22,2.8],def:[18,2.5],hp:[95,14],   exp:[65,7.5], gold:[28,4.5], areaIds:["stonecrypt","shadowpeaks","voidrift"]},
  {name:"Dark Sorcerer",   emoji:"🧙",desc:"Commands ancient spells.",   str:[35,4.0],def:[5,1.2], hp:[90,14],   exp:[90,10],  gold:[45,6.5], areaIds:["voidrift","ashvolcano"]},
  {name:"Banshee Queen",   emoji:"👸",desc:"Her scream alone can end you.",str:[32,3.8],def:[7,1.5],hp:[140,20],  exp:[100,11], gold:[50,7.0], areaIds:["voidrift","ashvolcano","frostspire"]},
  {name:"Lich Lord",       emoji:"💀",desc:"Mastered death itself.",      str:[40,4.5],def:[14,2.5],hp:[190,24],  exp:[130,14], gold:[65,9.0], areaIds:["ashvolcano","frostspire"]},
  {name:"Elder Dragon",    emoji:"🐲",desc:"A living catastrophe.",       str:[55,5.5],def:[20,3.2],hp:[320,38],  exp:[220,22], gold:[110,14], areaIds:["frostspire","shadowrealm"]},
  {name:"Void Titan",      emoji:"🌀",desc:"Born from the rift.",         str:[68,7.0],def:[28,4.0],hp:[450,48],  exp:[300,28], gold:[150,18], areaIds:["shadowrealm","celestialplane"]},
  {name:"Frost Wyrm",      emoji:"🧊",desc:"Freezes all it touches.",     str:[72,7.5],def:[32,4.5],hp:[500,54],  exp:[340,32], gold:[170,20], areaIds:["frostspire","shadowrealm"]},
  {name:"Shadow Demon",    emoji:"😈",desc:"Pure malice given form.",     str:[80,8.5],def:[38,5.0],hp:[560,60],  exp:[380,36], gold:[190,23], areaIds:["shadowrealm","celestialplane"]},
  {name:"Celestial Titan", emoji:"✨",desc:"A god that fell.",            str:[95,10.0],def:[48,6.5],hp:[750,82], exp:[500,48], gold:[250,30], areaIds:["celestialplane","abyssaldepths"]},
  {name:"Abyssal Horror",  emoji:"🌊",desc:"Should not exist.",           str:[115,12.0],def:[60,8.0],hp:[950,105],exp:[650,62],gold:[320,38], areaIds:["abyssaldepths","chaoscore"]},
  {name:"Chaos Incarnate", emoji:"☄️",desc:"The end. The beginning.",     str:[140,14.0],def:[80,10.0],hp:[1200,130],exp:[850,82],gold:[420,50],areaIds:["chaoscore"]},
].map(m=>({...m,image:`img/monsters/${slug(m.name)}.svg`}));

export const AVATARS=[
  {id:"av_wolf",     name:"Shadow Wolf",     emoji:"🐺",rarity:"rare",      dropRate:8,  desc:"Runs alone through the dark."},
  {id:"av_knight",   name:"Iron Knight",     emoji:"⚔️",rarity:"rare",      dropRate:8,  desc:"Steel and honour."},
  {id:"av_rogue",    name:"Night Rogue",     emoji:"🗡️",rarity:"rare",      dropRate:8,  desc:"Silent. Deadly. Gone."},
  {id:"av_ranger",   name:"Forest Ranger",   emoji:"🏹",rarity:"rare",      dropRate:7,  desc:"One with the wild."},
  {id:"av_mage",     name:"Storm Mage",      emoji:"🧙",rarity:"rare",      dropRate:7,  desc:"Commands lightning."},
  {id:"av_dragon",   name:"Dragonborn",      emoji:"🐉",rarity:"epic",      dropRate:3,  desc:"Blessed by ancient fire."},
  {id:"av_lich",     name:"Lich Ascendant",  emoji:"💀",rarity:"epic",      dropRate:3,  desc:"Death is just the beginning."},
  {id:"av_phoenix",  name:"Phoenix Risen",   emoji:"🔥",rarity:"epic",      dropRate:3,  desc:"Born from the ashes, again."},
  {id:"av_void",     name:"Void Walker",     emoji:"🌌",rarity:"epic",      dropRate:2,  desc:"Steps between worlds."},
  {id:"av_celestial",name:"Celestial Lord",  emoji:"✨",rarity:"legendary", dropRate:0.5,desc:"Touched by the gods."},
  {id:"av_chaos",    name:"Chaos Herald",    emoji:"🌀",rarity:"legendary", dropRate:0.5,desc:"Order fears this one."},
  {id:"av_champion", name:"Eternal Champion",emoji:"👑",rarity:"legendary", dropRate:0.4,desc:"The last one standing."},
].map(av=>({...av,image:`img/avatars/${av.id}.svg`}));

export const ITEMS=[
  {name:"Rusty Sword",          type:"Weapon", stat:"str", base:4,  minLevel:1,  rarity:"common",    emoji:"⚔️", dropRate:18, shopPrice:80},
  {name:"Wooden Club",          type:"Weapon", stat:"str", base:3,  minLevel:1,  rarity:"common",    emoji:"🪵", dropRate:18, shopPrice:60},
  {name:"Hunting Knife",        type:"Weapon", stat:"str", base:5,  minLevel:1,  rarity:"common",    emoji:"🔪", dropRate:16, shopPrice:90},
  {name:"Stone Axe",            type:"Weapon", stat:"str", base:4,  minLevel:2,  rarity:"common",    emoji:"🪓", dropRate:16, shopPrice:75},
  {name:"Shortbow",             type:"Weapon", stat:"str", base:5,  minLevel:3,  rarity:"common",    emoji:"🏹", dropRate:14, shopPrice:95},
  {name:"Iron Sword",           type:"Weapon", stat:"str", base:8,  minLevel:5,  rarity:"uncommon",  emoji:"⚔️", dropRate:12, shopPrice:220},
  {name:"Battle Axe",           type:"Weapon", stat:"str", base:9,  minLevel:5,  rarity:"uncommon",  emoji:"🪓", dropRate:12, shopPrice:240},
  {name:"War Hammer",           type:"Weapon", stat:"str", base:10, minLevel:6,  rarity:"uncommon",  emoji:"🔨", dropRate:11, shopPrice:260},
  {name:"Silver Blade",         type:"Weapon", stat:"str", base:12, minLevel:8,  rarity:"uncommon",  emoji:"🗡️", dropRate:10, shopPrice:400},
  {name:"Longbow",              type:"Weapon", stat:"str", base:11, minLevel:7,  rarity:"uncommon",  emoji:"🏹", dropRate:11, shopPrice:350},
  {name:"Crossbow",             type:"Weapon", stat:"str", base:13, minLevel:9,  rarity:"uncommon",  emoji:"🏹", dropRate:10, shopPrice:380},
  {name:"Flamebrand",           type:"Weapon", stat:"str", base:16, minLevel:12, rarity:"rare",      emoji:"🔥", dropRate:6},
  {name:"Shadowfang Dagger",    type:"Weapon", stat:"str", base:18, minLevel:14, rarity:"rare",      emoji:"🗡️", dropRate:5},
  {name:"Stormcaller Staff",    type:"Weapon", stat:"str", base:20, minLevel:16, rarity:"rare",      emoji:"🪄", dropRate:5},
  {name:"Dragonfang Blade",     type:"Weapon", stat:"str", base:22, minLevel:18, rarity:"rare",      emoji:"🔱", dropRate:5},
  {name:"Venomstrike Bow",      type:"Weapon", stat:"str", base:20, minLevel:15, rarity:"rare",      emoji:"🏹", dropRate:5},
  {name:"Runebreaker Axe",      type:"Weapon", stat:"str", base:24, minLevel:20, rarity:"rare",      emoji:"🪓", dropRate:4},
  {name:"Soulrender",           type:"Weapon", stat:"str", base:30, minLevel:25, rarity:"epic",      emoji:"💀", dropRate:2},
  {name:"Voidcaller Staff",     type:"Weapon", stat:"str", base:32, minLevel:28, rarity:"epic",      emoji:"🪄", dropRate:2},
  {name:"Stormfury Blade",      type:"Weapon", stat:"str", base:35, minLevel:30, rarity:"epic",      emoji:"⚡", dropRate:2},
  {name:"Abyssal Cleaver",      type:"Weapon", stat:"str", base:38, minLevel:35, rarity:"epic",      emoji:"🌀", dropRate:2},
  {name:"Doomcaster Wand",      type:"Weapon", stat:"str", base:36, minLevel:32, rarity:"epic",      emoji:"🪄", dropRate:2},
  {name:"Excalibur",            type:"Weapon", stat:"str", base:45, minLevel:10, rarity:"legendary", emoji:"⚡", dropRate:0.4},
  {name:"Godslayer",            type:"Weapon", stat:"str", base:55, minLevel:50, rarity:"legendary", emoji:"⚔️", dropRate:0.3},
  {name:"The Last Word",        type:"Weapon", stat:"str", base:60, minLevel:60, rarity:"legendary", emoji:"🔱", dropRate:0.3},
  {name:"Ragnarok",             type:"Weapon", stat:"str", base:70, minLevel:75, rarity:"legendary", emoji:"💥", dropRate:0.2},
  {name:"Eternal Flame",        type:"Weapon", stat:"str", base:50, minLevel:40, rarity:"legendary", emoji:"🔥", dropRate:0.3},
  {name:"Leather Cap",          type:"Helmet", stat:"def", base:3,  minLevel:1,  rarity:"common",    emoji:"🪖", dropRate:18, shopPrice:55},
  {name:"Cloth Hood",           type:"Helmet", stat:"def", base:3,  minLevel:1,  rarity:"common",    emoji:"🪖", dropRate:18, shopPrice:50},
  {name:"Wooden Helm",          type:"Helmet", stat:"def", base:4,  minLevel:2,  rarity:"common",    emoji:"🪖", dropRate:16, shopPrice:65},
  {name:"Iron Helm",            type:"Helmet", stat:"def", base:7,  minLevel:5,  rarity:"uncommon",  emoji:"⛑️", dropRate:11, shopPrice:300},
  {name:"Chain Coif",           type:"Helmet", stat:"def", base:8,  minLevel:6,  rarity:"uncommon",  emoji:"🪖", dropRate:11, shopPrice:320},
  {name:"Steel Helm",           type:"Helmet", stat:"def", base:9,  minLevel:8,  rarity:"uncommon",  emoji:"🪖", dropRate:10, shopPrice:360},
  {name:"Warden's Helm",        type:"Helmet", stat:"def", base:12, minLevel:12, rarity:"rare",      emoji:"🪖", dropRate:5},
  {name:"Shadowveil Hood",      type:"Helmet", stat:"def", base:14, minLevel:15, rarity:"rare",      emoji:"🪖", dropRate:5},
  {name:"Stormcrest Helm",      type:"Helmet", stat:"def", base:16, minLevel:18, rarity:"rare",      emoji:"⛑️", dropRate:4},
  {name:"Bonebreaker Skull",    type:"Helmet", stat:"def", base:18, minLevel:20, rarity:"rare",      emoji:"💀", dropRate:4},
  {name:"Void Visor",           type:"Helmet", stat:"def", base:24, minLevel:28, rarity:"epic",      emoji:"🪖", dropRate:2},
  {name:"Dreadhelm",            type:"Helmet", stat:"def", base:26, minLevel:30, rarity:"epic",      emoji:"😈", dropRate:2},
  {name:"Celestial Crown",      type:"Helmet", stat:"def", base:30, minLevel:38, rarity:"epic",      emoji:"✨", dropRate:2},
  {name:"Crown of the Fallen",  type:"Helmet", stat:"def", base:40, minLevel:20, rarity:"legendary", emoji:"👑", dropRate:0.3},
  {name:"Helm of Eternity",     type:"Helmet", stat:"def", base:50, minLevel:55, rarity:"legendary", emoji:"🌟", dropRate:0.2},
  {name:"Godking's Crown",      type:"Helmet", stat:"def", base:60, minLevel:70, rarity:"legendary", emoji:"👑", dropRate:0.2},
  {name:"Cloth Robe",           type:"Armour", stat:"def", base:3,  minLevel:1,  rarity:"common",    emoji:"👘", dropRate:18, shopPrice:65},
  {name:"Padded Vest",          type:"Armour", stat:"def", base:4,  minLevel:1,  rarity:"common",    emoji:"🦺", dropRate:18, shopPrice:70},
  {name:"Leather Armour",       type:"Armour", stat:"def", base:5,  minLevel:2,  rarity:"common",    emoji:"🦺", dropRate:16, shopPrice:85},
  {name:"Hide Armour",          type:"Armour", stat:"def", base:6,  minLevel:3,  rarity:"common",    emoji:"🦺", dropRate:14, shopPrice:95},
  {name:"Iron Chestplate",      type:"Armour", stat:"def", base:9,  minLevel:5,  rarity:"uncommon",  emoji:"🦺", dropRate:11, shopPrice:350},
  {name:"Chain Mail",           type:"Armour", stat:"def", base:10, minLevel:6,  rarity:"uncommon",  emoji:"🦺", dropRate:11, shopPrice:370},
  {name:"Steel Plate",          type:"Armour", stat:"def", base:12, minLevel:8,  rarity:"uncommon",  emoji:"🦺", dropRate:10, shopPrice:420},
  {name:"Battlemage Robe",      type:"Armour", stat:"def", base:11, minLevel:7,  rarity:"uncommon",  emoji:"👘", dropRate:10, shopPrice:390},
  {name:"Stormweave Armour",    type:"Armour", stat:"def", base:16, minLevel:14, rarity:"rare",      emoji:"🧥", dropRate:5},
  {name:"Shadowstitch Coat",    type:"Armour", stat:"def", base:18, minLevel:16, rarity:"rare",      emoji:"🧥", dropRate:5},
  {name:"Dragonscale Vest",     type:"Armour", stat:"def", base:20, minLevel:18, rarity:"rare",      emoji:"🦺", dropRate:4},
  {name:"Runeplate Armour",     type:"Armour", stat:"def", base:22, minLevel:20, rarity:"rare",      emoji:"🦺", dropRate:4},
  {name:"Voidweave Robe",       type:"Armour", stat:"def", base:28, minLevel:28, rarity:"epic",      emoji:"👘", dropRate:2},
  {name:"Phoenix Armour",       type:"Armour", stat:"def", base:30, minLevel:30, rarity:"epic",      emoji:"✨", dropRate:2},
  {name:"Abyssal Plate",        type:"Armour", stat:"def", base:35, minLevel:38, rarity:"epic",      emoji:"🌀", dropRate:2},
  {name:"Chaos Mantle",         type:"Armour", stat:"def", base:32, minLevel:35, rarity:"epic",      emoji:"☄️", dropRate:2},
  {name:"Dragonhide Armour",    type:"Armour", stat:"def", base:45, minLevel:25, rarity:"legendary", emoji:"🐉", dropRate:0.3},
  {name:"Aegis Robes",          type:"Armour", stat:"def", base:50, minLevel:45, rarity:"legendary", emoji:"✨", dropRate:0.3},
  {name:"Armour of the Gods",   type:"Armour", stat:"def", base:65, minLevel:70, rarity:"legendary", emoji:"⚡", dropRate:0.2},
  {name:"Wooden Shield",        type:"Shield", stat:"def", base:3,  minLevel:1,  rarity:"common",    emoji:"🛡️", dropRate:16, shopPrice:55},
  {name:"Worn Shield",          type:"Shield", stat:"def", base:4,  minLevel:1,  rarity:"common",    emoji:"🛡️", dropRate:16, shopPrice:70},
  {name:"Iron Shield",          type:"Shield", stat:"def", base:7,  minLevel:5,  rarity:"uncommon",  emoji:"🛡️", dropRate:11, shopPrice:280},
  {name:"Knight's Shield",      type:"Shield", stat:"def", base:9,  minLevel:6,  rarity:"uncommon",  emoji:"🛡️", dropRate:10, shopPrice:320},
  {name:"Tower Shield",         type:"Shield", stat:"def", base:11, minLevel:8,  rarity:"uncommon",  emoji:"🛡️", dropRate:10, shopPrice:380},
  {name:"Soulbind Shield",      type:"Shield", stat:"def", base:15, minLevel:14, rarity:"rare",      emoji:"🛡️", dropRate:5},
  {name:"Runeward Shield",      type:"Shield", stat:"def", base:18, minLevel:16, rarity:"rare",      emoji:"🛡️", dropRate:5},
  {name:"Voidguard",            type:"Shield", stat:"def", base:22, minLevel:22, rarity:"rare",      emoji:"🛡️", dropRate:4},
  {name:"Stormwall",            type:"Shield", stat:"def", base:28, minLevel:28, rarity:"epic",      emoji:"⚡", dropRate:2},
  {name:"Dawnbreaker Shield",   type:"Shield", stat:"def", base:32, minLevel:34, rarity:"epic",      emoji:"🌟", dropRate:2},
  {name:"Aegis of Eternity",    type:"Shield", stat:"def", base:42, minLevel:20, rarity:"legendary", emoji:"🌟", dropRate:0.3},
  {name:"The Immovable",        type:"Shield", stat:"def", base:55, minLevel:60, rarity:"legendary", emoji:"🛡️", dropRate:0.2},
  {name:"Cloth Leggings",       type:"Greaves",stat:"def", base:2,  minLevel:1,  rarity:"common",    emoji:"🦵", dropRate:16, shopPrice:45},
  {name:"Leather Greaves",      type:"Greaves",stat:"def", base:4,  minLevel:2,  rarity:"common",    emoji:"🦵", dropRate:16, shopPrice:65},
  {name:"Chain Greaves",        type:"Greaves",stat:"def", base:7,  minLevel:5,  rarity:"uncommon",  emoji:"🦵", dropRate:11, shopPrice:260},
  {name:"Steel Greaves",        type:"Greaves",stat:"def", base:9,  minLevel:7,  rarity:"uncommon",  emoji:"🦵", dropRate:10, shopPrice:310},
  {name:"Enchanted Greaves",    type:"Greaves",stat:"def", base:13, minLevel:12, rarity:"rare",      emoji:"🦵", dropRate:5},
  {name:"Shadowstep Leggings",  type:"Greaves",stat:"def", base:16, minLevel:16, rarity:"rare",      emoji:"🦵", dropRate:5},
  {name:"Voidwalker Greaves",   type:"Greaves",stat:"def", base:20, minLevel:22, rarity:"rare",      emoji:"🦵", dropRate:4},
  {name:"Shadow Greaves",       type:"Greaves",stat:"def", base:26, minLevel:28, rarity:"epic",      emoji:"🦵", dropRate:2},
  {name:"Celestial Greaves",    type:"Greaves",stat:"def", base:32, minLevel:36, rarity:"epic",      emoji:"✨", dropRate:2},
  {name:"Greaves of the Fallen",type:"Greaves",stat:"def", base:45, minLevel:40, rarity:"legendary", emoji:"💀", dropRate:0.3},
  {name:"Simple Boots",         type:"Boots",  stat:"def", base:2,  minLevel:1,  rarity:"common",    emoji:"👟", dropRate:16, shopPrice:45},
  {name:"Leather Boots",        type:"Boots",  stat:"def", base:3,  minLevel:2,  rarity:"common",    emoji:"👢", dropRate:16, shopPrice:55},
  {name:"Traveller's Boots",    type:"Boots",  stat:"def", base:4,  minLevel:3,  rarity:"common",    emoji:"👢", dropRate:14, shopPrice:70},
  {name:"Iron Boots",           type:"Boots",  stat:"def", base:6,  minLevel:5,  rarity:"uncommon",  emoji:"👢", dropRate:11, shopPrice:220},
  {name:"Ranger Boots",         type:"Boots",  stat:"def", base:7,  minLevel:6,  rarity:"uncommon",  emoji:"👢", dropRate:11, shopPrice:240},
  {name:"Swiftfoot Boots",      type:"Boots",  stat:"def", base:9,  minLevel:8,  rarity:"uncommon",  emoji:"👢", dropRate:10, shopPrice:280},
  {name:"Stormshard Boots",     type:"Boots",  stat:"def", base:12, minLevel:12, rarity:"rare",      emoji:"👢", dropRate:5},
  {name:"Shadowstride Boots",   type:"Boots",  stat:"def", base:15, minLevel:16, rarity:"rare",      emoji:"👢", dropRate:5},
  {name:"Voidstep Boots",       type:"Boots",  stat:"def", base:19, minLevel:22, rarity:"rare",      emoji:"👢", dropRate:4},
  {name:"Celestial Walkers",    type:"Boots",  stat:"def", base:25, minLevel:30, rarity:"epic",      emoji:"✨", dropRate:2},
  {name:"Boots of Eternity",    type:"Boots",  stat:"def", base:35, minLevel:45, rarity:"legendary", emoji:"🌟", dropRate:0.3},
  {name:"Godwalkers",           type:"Boots",  stat:"def", base:50, minLevel:65, rarity:"legendary", emoji:"⚡", dropRate:0.2},
  {name:"Copper Amulet",        type:"Amulet", stat:"def", base:2,  minLevel:1,  rarity:"common",    emoji:"📿", dropRate:14, shopPrice:50},
  {name:"Bone Necklace",        type:"Amulet", stat:"str", base:3,  minLevel:1,  rarity:"common",    emoji:"💀", dropRate:14, shopPrice:55},
  {name:"Wooden Charm",         type:"Amulet", stat:"def", base:3,  minLevel:2,  rarity:"common",    emoji:"🪵", dropRate:13, shopPrice:60},
  {name:"Mithril Ring",         type:"Amulet", stat:"def", base:7,  minLevel:5,  rarity:"uncommon",  emoji:"💍", dropRate:10, shopPrice:280},
  {name:"Warrior's Pendant",    type:"Amulet", stat:"str", base:8,  minLevel:5,  rarity:"uncommon",  emoji:"⚔️", dropRate:10, shopPrice:300},
  {name:"Jade Amulet",          type:"Amulet", stat:"def", base:9,  minLevel:7,  rarity:"uncommon",  emoji:"💚", dropRate:10, shopPrice:320},
  {name:"Runic Amulet",         type:"Amulet", stat:"str", base:12, minLevel:10, rarity:"rare",      emoji:"🔮", dropRate:5},
  {name:"Voidstone Pendant",    type:"Amulet", stat:"str", base:15, minLevel:14, rarity:"rare",      emoji:"🌀", dropRate:5},
  {name:"Soulfire Necklace",    type:"Amulet", stat:"str", base:18, minLevel:18, rarity:"rare",      emoji:"🔥", dropRate:4},
  {name:"Crystalheart",         type:"Amulet", stat:"def", base:20, minLevel:20, rarity:"rare",      emoji:"💎", dropRate:4},
  {name:"Void Amulet",          type:"Amulet", stat:"str", base:26, minLevel:28, rarity:"epic",      emoji:"💜", dropRate:2},
  {name:"Stormcaller's Eye",    type:"Amulet", stat:"str", base:30, minLevel:32, rarity:"epic",      emoji:"⚡", dropRate:2},
  {name:"Abyssal Heart",        type:"Amulet", stat:"def", base:28, minLevel:30, rarity:"epic",      emoji:"🌊", dropRate:2},
  {name:"Amulet of the Fallen", type:"Amulet", stat:"str", base:40, minLevel:20, rarity:"legendary", emoji:"💀", dropRate:0.3},
  {name:"Eye of the Void",      type:"Amulet", stat:"str", base:50, minLevel:50, rarity:"legendary", emoji:"👁️", dropRate:0.3},
  {name:"Godchain",             type:"Amulet", stat:"def", base:55, minLevel:60, rarity:"legendary", emoji:"✨", dropRate:0.2},
].map(item=>({...item,image:`img/items/${slug(item.name)}.svg`}));

export const PETS=[
  {name:"Baby Slime",    type:"Pet",stat:"def",base:6,  rarity:"common",   emoji:"🟢",desc:"Wobbly but loyal."},
  {name:"Forest Sprite", type:"Pet",stat:"str",base:7,  rarity:"common",   emoji:"🧚",desc:"Zips around your shoulder."},
  {name:"Tamed Rat",     type:"Pet",stat:"def",base:5,  rarity:"common",   emoji:"🐀",desc:"Surprisingly useful."},
  {name:"Shadow Cat",    type:"Pet",stat:"str",base:14, rarity:"uncommon", emoji:"🐈",desc:"Vanishes in dim light."},
  {name:"Storm Hawk",    type:"Pet",stat:"str",base:16, rarity:"uncommon", emoji:"🦅",desc:"Dives at your enemies."},
  {name:"Crystal Turtle",type:"Pet",stat:"def",base:18, rarity:"rare",     emoji:"🐢",desc:"A walking shield."},
  {name:"Baby Dragon",   type:"Pet",stat:"str",base:20, rarity:"rare",     emoji:"🐉",desc:"Breathes tiny flames."},
  {name:"Void Familiar", type:"Pet",stat:"str",base:30, rarity:"epic",     emoji:"👁️",desc:"Sees through walls."},
  {name:"Lava Pup",      type:"Pet",stat:"str",base:28, rarity:"epic",     emoji:"🔥",desc:"Always warm. Always angry."},
  {name:"Frost Wolf",    type:"Pet",stat:"def",base:32, rarity:"epic",     emoji:"🐺",desc:"Howls before every battle."},
  {name:"Ancient Phoenix",type:"Pet",stat:"str",base:50,rarity:"legendary",emoji:"🦅",desc:"Reborn every battle."},
  {name:"Celestial Crab", type:"Pet",stat:"def",base:55,rarity:"legendary",emoji:"🦀",desc:"Claws from another dimension."},
].map(p=>({...p,image:`img/pets/${slug(p.name)}.svg`}));

export const EGG_TYPES={
  common:   {id:"common",   name:"Common Egg",   emoji:"🥚", color:"#6b7280",incubationMs:5*60*1000,    rarityWeights:{common:75,uncommon:20,rare:5, epic:0, legendary:0},marketPrice:50},
  uncommon: {id:"uncommon", name:"Uncommon Egg", emoji:"🟡", color:"#059669",incubationMs:15*60*1000,   rarityWeights:{common:0, uncommon:60,rare:35,epic:5, legendary:0},marketPrice:300},
  rare:     {id:"rare",     name:"Rare Egg",     emoji:"🟠", color:"#2563eb",incubationMs:60*60*1000,   rarityWeights:{common:0, uncommon:0, rare:60,epic:35,legendary:5},marketPrice:1500},
  epic:     {id:"epic",     name:"Epic Egg",     emoji:"💜", color:"#7c3aed",incubationMs:4*60*60*1000, rarityWeights:{common:0, uncommon:0, rare:0, epic:80,legendary:20},marketPrice:6000},
  legendary:{id:"legendary",name:"Legendary Egg",emoji:"✨", color:"#d97706",incubationMs:12*60*60*1000,rarityWeights:{common:0, uncommon:0, rare:0, epic:50,legendary:50},marketPrice:20000},
};
export const SHINY_CHANCE=1/50;

export const DUNGEONS=[
  {
    id:"quick",name:"Quick Run",emoji:"⚡",
    desc:"A fast raid into the ruins. High XP efficiency.",
    durationMs:10*60*1000,
    minChests:0,maxChests:1,chestChance:0.45,
    expBase:120,expPerLevel:18,goldBase:40,goldPerLevel:8,
    color:"#2563eb",bgColor:"#eff6ff",borderColor:"#93c5fd",
  },
  {
    id:"expedition",name:"Expedition",emoji:"🗺️",
    desc:"A full dungeon run. Guaranteed rewards.",
    durationMs:60*60*1000,
    minChests:1,maxChests:3,chestChance:1.0,
    expBase:600,expPerLevel:60,goldBase:180,goldPerLevel:30,
    color:"#7c3aed",bgColor:"#f5f3ff",borderColor:"#c4b5fd",
  },
  {
    id:"delve",name:"Deep Delve",emoji:"💀",
    desc:"The depths below. Bring patience.",
    durationMs:5*60*60*1000,
    minChests:3,maxChests:8,chestChance:1.0,
    expBase:2800,expPerLevel:200,goldBase:800,goldPerLevel:120,
    color:"#dc2626",bgColor:"#fff1f2",borderColor:"#fca5a5",
  },
];

export const CHOICE_EVENTS=[
  {id:"wounded_knight",emoji:"⚔️",title:"A Wounded Knight",desc:"A knight slumped against a tree. Badly hurt. He reaches out a hand.",choices:[{label:"Help him",outcome:()=>{const r=Math.random();return r<0.5?{msg:"He thanks you and presses a coin pouch into your hand.",gold:()=>rand(40,100),hp:0}:{msg:"He thanks you weakly. That's all he has to give.",gold:0,hp:0};}},{label:"Leave him",outcome:()=>({msg:"You walk past. Some things aren't your problem.",gold:0,hp:0})}]},
  {id:"cursed_coin",emoji:"🪙",title:"A Glowing Coin",desc:"A single gold coin sits in the middle of the path, glowing faintly. Pick it up?",choices:[{label:"Pick it up",outcome:()=>{const r=Math.random();return r<0.4?{msg:"Just a coin. Lucky you!",gold:()=>rand(20,80),hp:0}:r<0.7?{msg:"It burns your hand! Cursed gold.",gold:0,hp:()=>-rand(10,30)}:{msg:"It vanishes the moment you touch it. Illusion.",gold:0,hp:0};}},{label:"Leave it",outcome:()=>({msg:"Some things are too good to be true.",gold:0,hp:0})}]},
  {id:"ancient_well",emoji:"🪣",title:"An Ancient Well",desc:"A stone well covered in moss. The bucket still works. Drink?",choices:[{label:"Drink from it",outcome:()=>{const r=Math.random();return r<0.5?{msg:"Cool and sweet. You feel refreshed.",gold:0,hp:()=>rand(20,50)}:r<0.75?{msg:"Tastes foul. Your stomach protests.",gold:0,hp:()=>-rand(10,25)}:{msg:"Nothing happens. Just water.",gold:0,hp:0};}},{label:"Move on",outcome:()=>({msg:"Probably wise. Ancient wells are risky.",gold:0,hp:0})}]},
  {id:"travelling_merchant",emoji:"🛒",title:"A Travelling Merchant",desc:"A cheerful merchant offers you a mystery item for 75 gold. No refunds.",choices:[{label:"Buy it (75 gold)",outcome:(p)=>{if((p.gold||0)<75)return{msg:"Not enough gold. He shrugs and moves on.",gold:0,hp:0};const r=Math.random();return r<0.4?{msg:"A health tonic! You drink it immediately.",gold:-75,hp:()=>rand(30,60)}:r<0.7?{msg:"A bag of gold! Net gain.",gold:()=>rand(5,75),hp:0}:{msg:"A rock. A painted rock. He's already gone.",gold:-75,hp:0};}},{label:"Decline",outcome:()=>({msg:"He tips his hat and disappears around the bend.",gold:0,hp:0})}]},
  {id:"haunted_tree",emoji:"🌳",title:"A Whispering Tree",desc:"An ancient tree with a face carved into it. It seems to whisper your name.",choices:[{label:"Listen closely",outcome:()=>{const r=Math.random();return r<0.33?{msg:"It reveals where something is buried nearby. Gold!",gold:()=>rand(50,150),hp:0}:r<0.66?{msg:"The whispers grow to screams. You flee, shaken.",gold:0,hp:()=>-rand(15,35)}:{msg:"It says: keep walking. You keep walking.",gold:0,hp:0};}},{label:"Back away slowly",outcome:()=>({msg:"Smart. Whispering trees are never a good sign.",gold:0,hp:0})}]},
  {id:"wounded_creature",emoji:"🐺",title:"A Wounded Animal",desc:"A small creature caught in a trap whimpers at you. Free it?",choices:[{label:"Free it",outcome:()=>{const r=Math.random();return r<0.5?{msg:"It licks your hand before bounding off. You feel good about that.",gold:0,hp:()=>rand(10,25)}:r<0.75?{msg:"It bites you for your trouble then runs. Ungrateful.",gold:0,hp:()=>-rand(5,15)}:{msg:"It drops something shiny as it flees.",gold:()=>rand(20,60),hp:0};}},{label:"Leave it",outcome:()=>({msg:"Nature is cruel. So are you, apparently.",gold:0,hp:0})}]},
  {id:"fortune_teller",emoji:"🔮",title:"A Fortune Teller",desc:"A veiled figure offers to read your future for 30 gold.",choices:[{label:"Pay 30 gold",outcome:(p)=>{if((p.gold||0)<30)return{msg:"She looks at your empty pockets and sighs.",gold:0,hp:0};const fortunes=["Gold finds those who walk far.","Your next battle will test you. Be ready.","A great item awaits around the next corner.","Trust no one who offers you something for free.","You will live. Probably."];const f=fortunes[Math.floor(Math.random()*fortunes.length)];return{msg:`She stares into the crystal and says: "${f}"`,gold:-30,hp:0};}},{label:"Keep walking",outcome:()=>({msg:"Your future remains unread. Probably fine.",gold:0,hp:0})}]},
  {id:"rope_bridge",emoji:"🌉",title:"A Rope Bridge",desc:"A rickety rope bridge over a deep gorge. Cross it or go the long way around?",choices:[{label:"Cross it",outcome:()=>{const r=Math.random();return r<0.6?{msg:"It holds! And you spot something glinting on the other side.",gold:()=>rand(30,80),hp:0}:r<0.85?{msg:"A rope snaps! You make it but not without bruises.",gold:0,hp:()=>-rand(15,30)}:{msg:"You cross safely. Nothing on the other side. Oh well.",gold:0,hp:0};}},{label:"Go around",outcome:()=>({msg:"Takes longer but your bones are intact.",gold:0,hp:0})}]},
  {id:"alchemist_fire",emoji:"🧪",title:"Bubbling Vials",desc:"An abandoned alchemist's pack. Several vials bubble ominously. Drink one?",choices:[{label:"Drink a vial",outcome:()=>{const r=Math.random();return r<0.35?{msg:"A healing elixir! Excellent find.",gold:0,hp:()=>rand(30,70)}:r<0.6?{msg:"Tastes like burning. Is burning.",gold:0,hp:()=>-rand(20,40)}:r<0.8?{msg:"Nothing. Probably just coloured water.",gold:0,hp:0}:{msg:"You find a coin hidden in the pack too!",gold:()=>rand(40,100),hp:()=>rand(10,30)};}},{label:"Leave them",outcome:()=>({msg:"Wise. Unlabelled potions are never a good idea.",gold:0,hp:0})}]},
  {id:"sleeping_giant",emoji:"👹",title:"A Sleeping Giant",desc:"A massive creature sleeps against a boulder. Its pockets look full. Rob it?",choices:[{label:"Pick its pocket",outcome:()=>{const r=Math.random();return r<0.5?{msg:"Success! Heavy coin pouch secured. You sprint away.",gold:()=>rand(80,200),hp:0}:{msg:"It wakes up! You run. It throws a rock. Ouch.",gold:0,hp:()=>-rand(20,45)};}},{label:"Sneak past",outcome:()=>({msg:"You tiptoe past. Living to fight another day.",gold:0,hp:0})}]},
  {id:"wishing_fountain",emoji:"⛲",title:"A Wishing Fountain",desc:"A pristine fountain in the middle of nowhere. Make a wish?",choices:[{label:"Toss in 10 gold",outcome:(p)=>{if((p.gold||0)<10)return{msg:"Not even 10 gold to spare. The fountain judges you.",gold:0,hp:0};const r=Math.random();return r<0.3?{msg:"The water glows! Your wish is granted.",gold:()=>rand(50,200),hp:0}:r<0.6?{msg:"The fountain bubbles warmly. You feel healthier.",gold:-10,hp:()=>rand(20,50)}:{msg:"Nothing happens. The gold sinks. The fountain doesn't care.",gold:-10,hp:0};}},{label:"Just look at it",outcome:()=>({msg:"Pretty fountain. You move on.",gold:0,hp:0})}]},
  {id:"dark_pact",emoji:"😈",title:"A Voice in the Dark",desc:"A voice offers you power in exchange for something. You can't quite make out what.",choices:[{label:"Accept",outcome:()=>{const r=Math.random();return r<0.4?{msg:"Power surges through you! (And something feels slightly wrong.)",gold:()=>rand(100,250),hp:0}:{msg:"You feel something leave you. Was that worth it?",gold:0,hp:()=>-rand(30,60)};}},{label:"Refuse",outcome:()=>({msg:"The voice sighs. Smart choice. Probably.",gold:0,hp:0})}]},
  {id:"chest",emoji:"📦",title:"A Weathered Chest",desc:"You stumble across an old chest half-buried in the dirt. Investigate?",choices:[{label:"Open it",outcome:()=>({msg:"The chest springs open! Gold inside!",gold:()=>rand(30,120),hp:0})},{label:"Leave it",outcome:()=>({msg:"You walk away. Better safe than sorry.",gold:0,hp:0})}]},
  {id:"stranger",emoji:"🧙",title:"A Hooded Stranger",desc:"A cloaked figure offers you something wrapped in cloth. Accept?",choices:[{label:"Accept",outcome:()=>({msg:"A strange potion. You drink it.",gold:0,hp:()=>rand(-20,40)})},{label:"Decline",outcome:()=>({msg:"The stranger vanishes in smoke.",gold:0,hp:0})}]},
  {id:"shrine",emoji:"⛩️",title:"Ancient Shrine",desc:"A crumbling shrine. Leave an offering of 50 gold?",choices:[{label:"Offer 50 gold",outcome:(p)=>{if((p.gold||0)<50)return{msg:"Not enough gold.",gold:0,hp:0};return{msg:"The shrine glows. You feel restored!",gold:-50,hp:()=>rand(20,60)};}},{label:"Ignore it",outcome:()=>({msg:"You pass by.",gold:0,hp:0})}]},
  {id:"gambler",emoji:"🎲",title:"Roadside Gambler",desc:"A shady figure offers to double 100 gold. Bet?",choices:[{label:"Bet 100 gold",outcome:(p)=>{if((p.gold||0)<100)return{msg:"Too broke to gamble.",gold:0,hp:0};const win=Math.random()<0.45;return{msg:win?"You won!":"The dice were loaded.",gold:win?100:-100,hp:0};}},{label:"Walk away",outcome:()=>({msg:"Some risks aren't worth it.",gold:0,hp:0})}]},
  {id:"mushroom",emoji:"🍄",title:"Glowing Mushroom",desc:"A bioluminescent mushroom pulses with strange light. Eat it?",choices:[{label:"Eat it",outcome:()=>{const r=Math.random();return{msg:r<0.4?"Delicious! You feel energised.":r<0.7?"Tastes awful.":"Nothing happens.",gold:0,hp:()=>Math.random()<0.4?rand(15,40):Math.random()<0.5?-rand(10,25):0};}},{label:"Leave it",outcome:()=>({msg:"You resist the glow.",gold:0,hp:0})}]},
  {id:"cave",emoji:"🕳️",title:"Dark Cave Entrance",desc:"A cave mouth yawns in the hillside. Enter?",choices:[{label:"Go in",outcome:()=>{const win=Math.random()<0.5;return{msg:win?"A cache of gold!":"A bat colony erupts! You flee.",gold:win?rand(40,100):-10,hp:win?0:-rand(5,15)};}},{label:"Move on",outcome:()=>({msg:"Some things are best left alone.",gold:0,hp:0})}]},
];

export const WALK_EVENTS=[
  {emoji:"🌿",text:"You walk through the quiet forest."},{emoji:"🍃",text:"Leaves rustle overhead. Nothing stirs."},
  {emoji:"🌧️",text:"A light rain begins to fall."},{emoji:"☀️",text:"The sun breaks through the canopy."},
  {emoji:"🌫️",text:"Fog rolls in from the valley below."},{emoji:"🍂",text:"Autumn leaves crunch under your boots."},
  {emoji:"❄️",text:"Your breath mists in the cold air."},{emoji:"🌙",text:"The moon watches from between the trees."},
  {emoji:"🦋",text:"A butterfly lands on your shoulder, then vanishes."},{emoji:"💀",text:"Bones of something large litter the clearing. Old."},
  {emoji:"👁️",text:"You feel like something is watching. Nothing there."},{emoji:"🕯️",text:"A lit candle sits on a stump. Who left it here?"},
  {emoji:"📦",text:"An empty chest sits open. Already looted."},{emoji:"⚔️",text:"Scorch marks scar the earth. A battle happened here."},
  {emoji:"🏰",text:"Ruins of something old crumble in the distance."},{emoji:"🧭",text:"Your compass spins once, then settles. Odd."},
  {emoji:"📯",text:"A distant horn sounds. Maybe a warning."},{emoji:"🪨",text:"Ancient stones mark the old road."},
  {emoji:"🌸",text:"Cherry blossoms drift across the path."},{emoji:"🎵",text:"You catch yourself humming. Not sure what song."},
  {emoji:"🔥",text:"Smoke rises to the east. Not your problem. Probably."},{emoji:"🐦",text:"A bird lands nearby, stares at you, then leaves. Rude."},
  {emoji:"👟",text:"Your boot comes untied. Again."},{emoji:"🌬️",text:"The wind blows your hair dramatically. Nobody saw it."},
  {emoji:"😴",text:"You yawn so hard your jaw pops. Time to keep moving."},{emoji:"🤔",text:"You could have sworn you've been here before."},
  {emoji:"💭",text:"You think about what you'd do with a million gold. Nice thought."},{emoji:"🦗",text:"Something bites you. Nothing there when you look."},
  {emoji:"🧦",text:"A single sock hangs from a branch. The mystery deepens."},{emoji:"📍",text:"Someone planted a flag here. For what? Unknown."},
  {emoji:"🗑️",text:"An empty potion bottle. Someone had a rough time here."},{emoji:"🩸",text:"A trail of something dark leads off the path. You don't follow."},
  {emoji:"🌀",text:"The air shimmers for a moment. Then nothing."},{emoji:"🔔",text:"A bell rings in the distance. No church for miles."},
  {emoji:"🪞",text:"A mirror propped against a tree. You don't look in it."},{emoji:"🧿",text:"An evil eye amulet dangles from a branch. Someone left a warning."},
  {emoji:"🕸️",text:"An enormous spiderweb blocks the trail. No spider in sight."},{emoji:"🌑",text:"The shadows move the wrong way for a moment."},
  {emoji:"📿",text:"Prayer beads scattered across the path. Recently dropped."},{emoji:"🚪",text:"A door frame stands alone in the forest. No walls. Just the door."},
  {emoji:"🪦",text:"A small grave marker. The name has worn away."},{emoji:"🌡️",text:"The temperature drops ten degrees and then returns. Strange."},
  {emoji:"👣",text:"Footprints in the mud. They stop suddenly. In the middle of nowhere."},{emoji:"🔮",text:"A crystal ball half buried in the dirt. Cloudy inside."},
  {emoji:"🗺️",text:"A torn map flutters past. Nowhere you recognize."},{emoji:"🏹",text:"An arrow is lodged in a tree. Still quivering."},
  {emoji:"🛡️",text:"A cracked shield leans against a rock. Its owner moved on."},{emoji:"⛺",text:"An abandoned campsite. The fire is still warm."},
  {emoji:"🔑",text:"A rusty key on the ground. No lock in sight."},{emoji:"📜",text:"A torn piece of parchment. The writing is smudged beyond reading."},
  {emoji:"🧲",text:"Your gear tugs slightly in one direction. Odd."},{emoji:"💎",text:"Something glints in the dirt. Just a piece of glass. Still pretty."},
  {emoji:"🪤",text:"You nearly step on a trap. Nearly."},{emoji:"🎒",text:"Someone's pack lies abandoned by the road."},
  {emoji:"🔭",text:"A spyglass hanging from a branch. Someone was watching something."},{emoji:"🦊",text:"A fox crosses your path and gives you a judgemental look."},
  {emoji:"🐺",text:"A distant howl echoes through the trees. Then silence."},{emoji:"🦅",text:"A hawk circles overhead for a while, then moves on."},
  {emoji:"🐍",text:"A snake slithers across the path and disappears into the brush."},{emoji:"🐗",text:"Sounds of something large crashing through the undergrowth. It moves away."},
  {emoji:"🐾",text:"Large paw prints in the mud. Very large."},{emoji:"🦉",text:"An owl watches you from a low branch. In the middle of the day."},
  {emoji:"🐉",text:"Something huge flew over — very high up. Gone before you could be sure."},{emoji:"🐜",text:"A column of ants marches across your boot. They have somewhere to be."},
  {emoji:"🦎",text:"A lizard basks on a warm rock. It doesn't move as you pass."},{emoji:"🐸",text:"Hundreds of frogs. Then none. All at once."},
  {emoji:"🌈",text:"A rainbow appears. It points somewhere. Maybe useful."},{emoji:"⚡",text:"Lightning strikes nearby. No clouds in sight."},
  {emoji:"🌋",text:"The ground rumbles faintly. Nothing more."},{emoji:"☄️",text:"Something streaks across the sky. Too fast to track."},
  {emoji:"🌪️",text:"A tiny whirlwind of leaves spirals up and fades."},{emoji:"🌤️",text:"Perfect weather today. You almost feel safe."},
  {emoji:"🌧️",text:"Rain begins suddenly, then stops just as fast."},{emoji:"❄️",text:"A single snowflake falls. Just one. In summer."},
  {emoji:"🧙",text:"A hooded figure walks in the opposite direction. Doesn't acknowledge you."},{emoji:"👴",text:"An old man sits by the road. Asleep, or pretending."},
  {emoji:"🧟",text:"Something shuffles in the bushes. It shuffles away."},{emoji:"🎪",text:"Distant music carries on the wind. Happy music. Out here."},
  {emoji:"🏇",text:"Hoofbeats thunder past on a parallel road. Gone in seconds."},{emoji:"😤",text:"You trip on a root. No one saw that. Probably."},
  {emoji:"💨",text:"A tumbleweed rolls by. Where did that even come from?"},
];

function rand(a,b){return Math.floor(Math.random()*(b-a+1))+a;}
